### ISSUE TITLE
"Connet failed" after clicking Connect button in AdsServerSample

### ISSUE THREAD

**Issue by ali50m** [Beckhoff/TF6000_ADS_DOTNET_V4_Samples#4]
Thanks for the update of "x86" hint, I can start up the AdsServerSample application now.  Click the connection button will cause an exception and promp "Connect failed". Please let me know if there is more set up to run this demo.

![image](https://user-images.githubusercontent.com/9393831/184264476-dc53b2b5-c983-4aaf-b5d7-485055eeb504.png)

![image](https://user-images.githubusercontent.com/9393831/184264522-a370379b-db33-45ac-98e9-125de2841468.png)

![image](https://user-images.githubusercontent.com/9393831/184264564-e27e70b8-532c-4295-b7c9-4f50f6264858.png)

**Comment by ali50m** [comment]
what has been installed:

TwinCAT 2.11 x64 Engineering v2.11.2307.0
visual studio 2022.3 Version 17.3.0
windows 10 64bit 21h2 19044.1889

**Comment by RalfHeitmann** [comment]
The reason for the problem was, that the example used an 'dynamic' / 'unfixed' port for the AdsSampleServer. This works with new er TwinCAT systems, but not with the 2.11.2307 Engineering. But anyhow, in your own AdsServer implementations a fixed AmsPort should be used for AdsServers (between 25000 and 25999). I changed the sample and it works now properly as 32-Bit process also under 2.11.2307 Engineering.
